BudgetAsp/Models/Account.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BudgetAsp.Models
{
    public class Account : IEntity
    {
        public long Id { get; set; }
        public bool Deleted { get; set; }
        public DateTime DateCreated { get; set; }
        public DateTime DateUpdated { get; set; }

        [Required, StringLength(100, MinimumLength = 3)]
        public string Name { get; set; }
        
        public ICollection<Transaction> Transactions { get; set; }
        
        public long UserId { get; set; }
        public User User { get; set; }
    }
    
    public interface IAccountRepository: IRepository<Account>
    {
        
    }

    public class AccountRepository : BaseRepository<Account>, IAccountRepository
    {
        public AccountRepository(BudgetContext context)
        {
            Context = context;
        }
    }
}

BudgetAsp/Controllers/AccountsController.cs
using System.Threading.Tasks;
using BudgetAsp.Models;
using Microsoft.AspNetCore.Mvc;

namespace BudgetAsp.Controllers
{
    public class AccountsController : Controller
    {
        private readonly IAccountRepository _repository;

        public AccountsController(IAccountRepository repository)
        {
            _repository = repository;
        }
        
        // GET
        public async Task<IActionResult> Index()
        {
            var accounts = await _repository.GetAllActiveOnly();
            
            return View(accounts);
        }

        public IActionResult New()
        {
            var account = new Account();
            
            return View(account);
        }

        public async Task<IActionResult> Create(Account account)
        {
            if (!ModelState.IsValid)
            {
                return View(nameof(New));
            }
            else
            {
                account.UserId = 1;
                
                await _repository.Save(account);
                TempData["message"] = "Account Saved";
                return RedirectToAction(nameof(Index));
            }
        }

        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            var account = await _repository.Get(id.Value);

            if (account == null)
            {
                return NotFound();
            }

            return View(account);
        }

        public async Task<IActionResult> Update(long? id, Account account)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            var editing = await _repository.Get(id.Value);

            if (editing == null)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                return View(nameof(Edit));
            }

            editing.Name = account.Name;

            await _repository.Save(editing);
            TempData["message"] = "Account Saved";
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            await _repository.Delete(id.Value);
            TempData["message"] = "Account Deleted";
            return RedirectToAction(nameof(Index));
        }
    }
}

BudgetAsp/Controllers/TransactionsController.cs
using System.Diagnostics;
using System.Threading.Tasks;
using BudgetAsp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace BudgetAsp.Controllers
{
    public class TransactionsController : Controller
    {
        private readonly ITransactionRepository _repository;
        private readonly ILogger<TransactionsController> _logger;

        public TransactionsController(ITransactionRepository repository, ILogger<TransactionsController> logger)
        {
            _repository = repository;
            _logger = logger;
        }
        
        // GET
        public async Task<IActionResult> Index(long accountId)
        {
            var transactions = await _repository.GetAllActiveByForAccount(accountId);
            
            return View(transactions);
        }

        // public IActionResult New()
        // {
        //     var transaction = new Transaction();
        //     
        //     return View(transaction);
        // }
        //
        // public async Task<IActionResult> Create(Transaction transaction)
        // {
        //     if (!ModelState.IsValid)
        //     {
        //         return View(nameof(New));
        //     }
        //     else
        //     {
        //         transaction.UserId = 1;
        //         
        //         await _repository.Save(transaction);
        //         TempData["message"] = "Transaction Saved";
        //         return RedirectToAction(nameof(Index));
        //     }
        // }
        //
        // public async Task<IActionResult> Edit(long? id)
        // {
        //     if (id == null)
        //     {
        //         return NotFound();
        //     }
        //     
        //     var transaction = await _repository.Get(id.Value);
        //
        //     if (transaction == null)
        //     {
        //         return NotFound();
        //     }
        //
        //     return View(transaction);
        // }
        //
        // public async Task<IActionResult> Update(long? id, Transaction transaction)
        // {
        //     if (id == null)
        //     {
        //         return NotFound();
        //     }
        //     
        //     var editing = await _repository.Get(id.Value);
        //
        //     if (editing == null)
        //     {
        //         return NotFound();
        //     }
        //
        //     if (!ModelState.IsValid)
        //     {
        //         return View(nameof(Edit));
        //     }
        //
        //     // editing.Name = transaction.Name;
        //
        //     await _repository.Save(editing);
        //     TempData["message"] = "Account Saved";
        //     return RedirectToAction(nameof(Index));
        // }
        //
        // public async Task<IActionResult> Delete(long? id)
        // {
        //     if (id == null)
        //     {
        //         return NotFound();
        //     }
        //     
        //     await _repository.Delete(id.Value);
        //     TempData["message"] = "Account Deleted";
        //     return RedirectToAction(nameof(Index));
        // }
    }
}

BudgetAsp/Views/Accounts/Edit.cshtml
@model Account

@{
    ViewBag.Title = "Edit Account";
    Layout = "_Layout";
}

<h2 class="title is-2">Edit Account</h2>

<form asp-action="Update" method="post">
    <input asp-for="Id" type="hidden">

    <div class="field">
        <label asp-for="Name" class="label"></label>
        <div class="control">
            <input type="text" asp-for="Name" class="input">
        </div>
        <span asp-validation-for="Name" class="help is-danger"></span>
    </div>

    <div class="field is-grouped">
        <div class="control">
            <button type="submit" class="button is-primary">Save</button>
        </div>
        <div class="control">
            <a asp-action="Index" class="button is-danger">Cancel</a>
        </div>
    </div>
</form>

@section Scripts
{
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

BudgetAsp/Views/Accounts/Index.cshtml
@model List<Account>

@{
    ViewBag.Title = "Accounts";
    Layout = "_Layout";
}

<div class="level">
    <div class="level-left">
        <div class="level-item">
            <h2 class="title is-2">Accounts</h2>
        </div>
    </div>
    <div class="level-right">
        <div class="level-item">
            <a class="button is-primary" asp-action="New">New</a>
        </div>
    </div>
</div>

@if (TempData.ContainsKey("Message"))
{
    <div class="notification is-info is-light mt-3">
        <button class="delete"></button>
        @TempData["Message"]
    </div>
}

@if (Model.Any())
{
    <table class="table is-fullwidth">
        <thead>
        <tr>
            <th>Name</th>
            <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var account in Model)
        {
            <tr>
                <td><a asp-controller="Transactions" asp-route-accountId="@account.Id">@account.Name</a></td>
                <td><a asp-action="Edit" asp-route-id="@account.Id" class="button is-info is-small">Edit</a> | <a asp-action="Delete" asp-route-id="@account.Id" class="button is-danger is-small">Delete</a></td>
            </tr>
        }
        </tbody>
    </table>
}
else
{
    <section class="hero is-primary">
        <div class="hero-body">
            <p class="title">
                Add some accounts to get started.
            </p>
        </div>
    </section>
}

BudgetAsp/Views/Accounts/New.cshtml
@model Account

@{
    ViewBag.Title = "New Account";
    Layout = "_Layout";
}

<h2 class="title is-2">New Account</h2>

<form asp-action="Create" method="post">
    <div class="field">
        <label asp-for="Name" class="label"></label>
        <div class="control">
            <input type="text" asp-for="Name" class="input">
        </div>
        <span asp-validation-for="Name" class="help is-danger"></span>
    </div>

    <div class="field is-grouped">
        <div class="control">
            <button type="submit" class="button is-primary">Save</button>
        </div>
        <div class="control">
            <a asp-action="Index" class="button is-danger">Cancel</a>
        </div>
    </div>
</form>

@section Scripts
{
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}