BudgetAsp/Controllers/AccountsController.cs
using System.Threading.Tasks;
using BudgetAsp.Models;
using Microsoft.AspNetCore.Mvc;

namespace BudgetAsp.Controllers
{
    public class AccountsController : Controller
    {
        private readonly IAccountRepository _repository;

        public AccountsController(IAccountRepository repository)
        {
            _repository = repository;
        }
        
        // GET
        public async Task<IActionResult> Index()
        {
            var accounts = await _repository.GetAllActiveOnly();
            
            return View(accounts);
        }

        public IActionResult New()
        {
            var account = new Account();
            
            return View(account);
        }

        public async Task<IActionResult> Create(Account account)
        {
            if (!ModelState.IsValid)
            {
                return View(nameof(New));
            }
            else
            {
                account.UserId = 1;
                
                await _repository.Save(account);
                TempData["message"] = "Account Saved";
                return RedirectToAction(nameof(Index));
            }
        }

        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            var account = await _repository.Get(id.Value);

            if (account == null)
            {
                return NotFound();
            }

            return View(account);
        }

        public async Task<IActionResult> Update(long? id, Account account)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            var editing = await _repository.Get(id.Value);

            if (editing == null)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                return View(nameof(Edit));
            }

            editing.Name = account.Name;

            await _repository.Save(editing);
            TempData["message"] = "Account Saved";
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            await _repository.Delete(id.Value);
            TempData["message"] = "Account Deleted";
            return RedirectToAction(nameof(Index));
        }
    }
}

BudgetAsp/Controllers/CategoriesController.cs
using System.Threading.Tasks;
using BudgetAsp.Models;
using Microsoft.AspNetCore.Mvc;

namespace BudgetAsp.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly ICategoryRepository _repository;

        public CategoriesController(ICategoryRepository repository)
        {
            _repository = repository;
        }
        
        // GET
        public async Task<IActionResult> Index()
        {
            var categories = await _repository.GetAllActiveOnly();
            
            return View(categories);
        }

        public IActionResult New()
        {
            var category = new Category();
            
            return View(category);
        }

        public async Task<IActionResult> Create(Category category)
        {
            if (!ModelState.IsValid)
            {
                return View("New");
            }
            else
            {
                category.UserId = 1;
                
                await _repository.Save(category);
                TempData["message"] = "Category Saved";
                return RedirectToAction("Index");
            }
        }

        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            var category = await _repository.Get(id.Value);

            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        public async Task<IActionResult> Update(long? id, Category category)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            var editing = await _repository.Get(id.Value);

            if (editing == null)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                return View("Edit");
            }

            editing.Name = category.Name;

            await _repository.Save(editing);
            TempData["message"] = "Category Saved";
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            await _repository.Delete(id.Value);
            TempData["message"] = "Category Deleted";
            return RedirectToAction(nameof(Index));
        }
    }
}

BudgetAsp/Controllers/PayeesController.cs
using System.Threading.Tasks;
using BudgetAsp.Models;
using Microsoft.AspNetCore.Mvc;

namespace BudgetAsp.Controllers
{
    public class PayeesController : Controller
    {
        // GET
        private readonly IPayeeRepository _repository;

        public PayeesController(IPayeeRepository repository)
        {
            _repository = repository;
        }
        
        // GET
        public async Task<IActionResult> Index()
        {
            var payees = await _repository.GetAllActiveOnly();
            
            return View(payees);
        }

        public IActionResult New()
        {
            var payee = new Payee();
            
            return View(payee);
        }

        public async Task<IActionResult> Create(Payee payee)
        {
            if (!ModelState.IsValid)
            {
                return View("New");
            }
            else
            {
                payee.UserId = 1;
                
                await _repository.Save(payee);
                TempData["message"] = "Payee Saved";
                return RedirectToAction("Index");
            }
        }

        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            var payee = await _repository.Get(id.Value);

            if (payee == null)
            {
                return NotFound();
            }

            return View(payee);
        }

        public async Task<IActionResult> Update(long? id, Payee payee)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            var editing = await _repository.Get(id.Value);

            if (editing == null)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                return View("Edit");
            }

            editing.Name = payee.Name;

            await _repository.Save(editing);
            TempData["message"] = "Payee Saved";
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            
            await _repository.Delete(id.Value);
            TempData["message"] = "Payee Deleted";
            return RedirectToAction(nameof(Index));
        }
    }
}

BudgetAsp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width"/>
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer"/>
</head>
<body>
<div>
    <nav class="navbar is-primary" role="navigation">
        <div class="container">
            <div class="navbar-brand">
                <a asp-controller="Home" asp-action="Index" class="nav-item">
                    <span class="icon is-large">
                        <i class="fas fa-2x fa-home"></i>
                    </span>
                </a>

                <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                </a>
            </div>
            <div class="navbar-menu">
                <div class="navbar-start">
                    <a href="#" class="navbar-item">Dashboard</a>
                    <a asp-controller="Accounts" asp-action="Index" class="navbar-item">Accounts</a>
                    <div class="navbar-item has-dropdown is-hoverable">
                        <a href="#" class="navbar-link">Settings</a>
                        <div class="navbar-dropdown">
                            <a asp-controller="Categories" asp-action="Index" class="navbar-item">Categories</a>
                            <a asp-controller="Payees" asp-action="Index" class="navbar-item">Payees</a>
                        </div>
                    </div>
                </div>

                <div class="navbar-end">
                    <div class="navbar-item">
                        <div class="buttons">
                            <a href="#" class="button is-link">
                                <bold>Sign in</bold>
                            </a>
                            <a href="#" class="button is-danger">Sign out</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </nav>
    <section class="section">
        <div class="container">
            @RenderBody()
        </div>
    </section>
</div>
<script src="~/js/site.js"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>